# .github/workflows/imagepush.yml
name: Docker Image Build and Push

on:
  workflow_call:

jobs:
  image_push:
    runs-on: myrunner-2
    env:
      DOCKER_IMAGE: tobadocker12/petapp:${{ github.sha }}

    steps:
      - name: Ensure Docker is Installed and Running
        run: |
          if ! command -v docker &> /dev/null; then
            echo "Docker not found. Installing..."
            sudo yum update -y
            sudo yum install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker $USER
          else
            echo "Docker is already installed."
          fi
          sudo systemctl restart docker
          docker --version

      - name: Build Docker Image
        run: |
          docker build -t $DOCKER_IMAGE .
          docker save $DOCKER_IMAGE > docker_image.tar

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: docker_image.tar

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: docker push $DOCKER_IMAGE
