# .github/workflows/imagepush.yml
name: Docker Image Build and Push

on:
  workflow_call:

jobs:
  image_push:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: tobadocker12/petapp:${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build project with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker Image
        run: |
          docker build -t $DOCKER_IMAGE .
          docker save $DOCKER_IMAGE > docker_image.tar

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: docker_image.tar

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: docker push $DOCKER_IMAGE



        
