name: Build

on: 
  workflow_call:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      # Ensure Maven is installed
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven
        run: mvn clean install

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: target/*.jar



      - name: Configure JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
          version: latest
        env:
          JF_URL: https://trialuz45a9.jfrog.io

      - name: Authenticate JFrog CLI
        run: |
          jf c add my-artifactory \
            --url=https://trialuz45a9.jfrog.io/artifactory \
            --access-token=${{ secrets.JFROG_TOKEN }}
            
      - name: Verify JFrog CLI
        run: jf -v

      - name: Upload Artifact to JFrog
        run: |
          jf rt u "target/*.jar" "DevSecOps-JF/"
