name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17 (adopt)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Install Maven (if cache miss)
        if: steps.cache-maven-dependencies.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update && sudo apt-get install -y maven
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Build with Maven
        run: mvn clean install

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: target/*.jar
          
      - name: Configure JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
            version: latest
        env:
            JF_URL: https://trialp9y8bu.jfrog.io
            JF_ACCESS_TOKEN: ${{ secrets.JFROG_TOKEN }}

      - name: Upload Artifact to JFrog (use wildcard for all jars)
        run: |
          jf rt u "target/*.jar" "DevSecOps-JF/"
