name: Build

on: 
  workflow_call:

jobs:
  build:
    runs-on: DevSecOps
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17 (adopt)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      # Install Maven only if cache miss (improves performance)...
      - name: Install Maven (if cache miss)
        run: |
          sudo apt-get update && sudo apt-get install -y maven
        env:
          DEBIAN_FRONTEND: noninteractive
          if: steps.cache-maven-dependencies.outputs == ''

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven
        run: mvn clean install

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: target/*.jar
          

      # - name: Configure JFrog CLI (latest version)
      #   uses: jfrog/setup-jfrog-cli@v3
      #   with:
      #     version: 'latest'
      #   env:
      #     JF_URL: https://trialuz45a9.jfrog.io

      # - name: Authenticate JFrog CLI
      #   run: |
      #     jf c add DevSecOps-JF \
      #       --url=https://trialuz45a9.jfrog.io/artifactory \
      #       --access-token=${{ secrets.JFROG_TOKEN }} \
      #       --overwrite=true

      # - name: Verify JFrog CLI
      #   run: jf -v

      # - name: Upload Artifact to JFrog (use wildcard for all jars)
      #   run: jf rt u "target/*.jar" "DevSecOps-JF/"

      - name: Configure JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
          version: latest
        env:
          JF_URL: https://trialuz45a9.jfrog.io
          JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
          
      - name: Check JFrog CLI version
        run: |
           which jf
           jf --version

      - name: Authenticate JFrog CLI
        run: |
          jf c add DevSecOps-JF \
            --url=https://trialuz45a9.jfrog.io/artifactory \
            --access-token=${{ secrets.JFROG_TOKEN }} \
            --overwrite=true
        
      - name: Upload Artifact to JFrog (use wildcard for all jars)
        run: |
            jf rt u "target/*.jar" "DevSecOps-JF/"

      # - name: Configure JFrog CLI
      #   uses: jfrog/setup-jfrog-cli@v3
      #   with:
      #     version: latest
      #   env:
      #     JF_URL: https://trialp9y8bu.jfrog.io
      #     JF_ACCESS_TOKEN: ${{ secrets.JFROG_TOKEN }}
      # - name: Upload JAR to JFrog
      #   run: |
      #      sudo jf rt u "target/*.jar" "DevSecOps-JF/"
