name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Recommend using the latest version

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # 'temurin' is the newer default
          cache: maven

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Authenticate with AWS CodeArtifact
        id: auth-codeartifact
        run: |
          CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
            --domain toba-artifact \
            --domain-owner 575108950135 \
            --region us-west-2 \
            --query authorizationToken \
            --output text)
          echo "CODEARTIFACT_AUTH_TOKEN=$CODEARTIFACT_AUTH_TOKEN" >> $GITHUB_ENV

          CODEARTIFACT_URL=$(aws codeartifact get-repository-endpoint \
            --domain toba-artifact \
            --domain-owner 575108950135 \
            --repository DevSecOps-Artifact \
            --format maven \
            --region us-west-2 \
            --query repositoryEndpoint \
            --output text)
          echo "CODEARTIFACT_URL=$CODEARTIFACT_URL" >> $GITHUB_ENV

      - name: Configure Maven to use AWS CodeArtifact
        run: |
            mkdir -p ~/.m2
            cat <<EOF > ~/.m2/settings.xml
                      <settings>
                        <servers>
                          <server>
                            <id>toba-artifact-DevSecOps-Artifact</id>
                            <username>aws</username>
                            <password>${CODEARTIFACT_AUTH_TOKEN}</password>
                          </server>
                        </servers>
                        <mirrors>
                          <mirror>
                            <id>toba-artifact-DevSecOps-Artifact</id>
                            <name>toba-artifact-DevSecOps-Artifact</name>
                            <url>${CODEARTIFACT_URL}</url>
                            <mirrorOf>*</mirrorOf>
                          </mirror>
                        </mirrors>
                        <profiles>
                          <profile>
                            <id>toba-artifact-DevSecOps-Artifact</id>
                            <activation>
                              <activeByDefault>true</activeByDefault>
                            </activation>
                            <repositories>
                              <repository>
                                <id>toba-artifact-DevSecOps-Artifact</id>
                                <url>${CODEARTIFACT_URL}</url>
                              </repository>
                            </repositories>
                          </profile>
                        </profiles>
                      </settings>
                      EOF


      - name: Build Project
        run: mvn clean install --settings ~/.m2/settings.xml

      - name: Publish to AWS CodeArtifact
        run: mvn deploy --settings ~/.m2/settings.xml
