name: Sonar Scan

on:
  workflow_call:

jobs:
  sonar:
    runs-on: myrunner-2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SonarCloud Scan
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=Toba0z_DevSecOps_pipeline_PJ \
            -Dsonar.organization=toba0z \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
       