# .github/workflows/sonar.yml
name: Sonar Scan

on:
 workflow_call:

jobs:
  sonar:
    runs-on: ubuntu-latest
    #needs: build  # Ensures Sonar runs after build succeeds
    steps:
      - name: SonarCloud Scan
        run: |
         mvn sonar:sonar \
          -Dsonar.projectKey=Toba0z_DevSecOps_pipeline_PJ \
          -Dsonar.organization=toba0z \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}