name: Sonar Scan Workflow

on:
  workflow_call:

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      # Call the reusable build workflow
      - name: Run Build Workflow
        uses: ./.github/workflows/build.yml

      # Download build artifacts
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: jar

      # Run Sonar Scan
      - name: SonarCloud Scan
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=Toba0z_DevSecOps_pipeline_PJ \
            -Dsonar.organization=toba0z \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
