name: Sonar Scan

on:
  workflow_call:

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'  # Specify JDK 17

      - name: SonarCloud Scan
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=Toba0z_DevSecOps_pipeline_PJ \
            -Dsonar.organization=toba0z \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        working-directory: ./  # Use './' if pom.xml is in the root, or specify the correct subdirectory