name: Sonar Scan

on:
  workflow_call:

jobs:
  sonar:
    runs-on: myrunner-2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'  # Use Temurin JDK (Recommended)
          java-version: '17'        # Match your project's Java version

      - name: Build Project
        run: mvn clean package -DskipTests  # Skipping tests to save time

      - name: SonarCloud Scan
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=Toba0z_DevSecOps_pipeline_PJ \
            -Dsonar.organization=toba0z \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.java.binaries=target/classes  # Ensure SonarQube finds compiled classes
