# .github/workflows/sonar.yml
#
# on:
#  workflow_call:

# jobs:
#   sonar:
#     runs-on: java_build
#     #needs: build  # Ensures Sonar runs after build succeeds
#     steps:
#       - name: SonarCloud Scan
#         run: mvn sonar:sonar -Dsonar.projectKey=Toba0z_DevSecOps_pipeline_PJ -Dsonar.organization=toba0z -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=3efd906389f89ff2f42493c5bda21481a0a75a68

name: Sonar Scan

on:
  workflow_call:

jobs:
  sonar:
    runs-on: [self-hosted, DevSecOps_runner]
    steps:
      - name: SonarCloud Scan
        run: mvn sonar:sonar \
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
          -Dsonar.organization=${{ secrets.SONAR_ORG }} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
