# .github/workflows/test.yml
name: Test

on:
 workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest # Use your self-hosted runner
    #needs: build  # Ensures test only runs after build succeeds
    steps:
      - name: Run Unit Tests
        run: mvn test

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/test-classes/TEST-*.xml
